name: "Template"
description: "Apply a template to a project"
requirements: "true"
applicable: "true"
inputs:
    source:
        long_name: "Template source directory"
        description: "The path the template is located at relative to the feature root"
        type: string
        required: true
    destination:
        long_name: "Destination directory"
        description: "The path to write the template to relative to the current directory"
        type: string
        required: true
    overwrite:
        long_name: "Overwrite existing files"
        description: "Indicates existing files should be overwritten"
        type: boolean
        default: false
        required: true
    variables:
        description: "Template variables"
        type: object
        default: {}
        required: false
